### ISSUE TITLE
Scanning through Proxy

### ISSUE THREAD

**Issue by mschilt** [rbsec/sslscan#121]
Being able to scan through a HTTP proxy (by using CONNECT xx.xx.xx.xx) would be great.

**Comment by rbsec** [comment]
Scanning will not be possible through HTTP CONNECT, because when you issue a CONNECT command the server you're talking to makes its own connection to the target - so you would be unable to see any information about the ciphers that are used.

If you need to scan through a proxy then there are third party tools that should be able to wrap sslscan like Tsocks or poxychains.
