### ISSUE TITLE
OpenSSL 1.1.0

### ISSUE THREAD

**Issue by tunkaflux** [rbsec/sslscan#126]
Hello,

This is more of a general question, but how will the move to OpenSSL 1.1.0 eventually look like? It has support for additional encryption options, however SSLv2 has been removed for instance. Does that mean sslscan will always have to use OpenSSL 1.0.x to detect SSLv2 servers/services?

**Comment by anthraxx** [comment]
Any ideas about this? As we actually need to build this against openssl 1.1.0 but its not quite possible

**Comment by rbsec** [comment]
OpenSSL 1.1.0 introduced a number of significant changes, including the removal of old and insecure features such as SSLv2. While this is a very good thing for the SSL ecosystem as a whole, it is a problem for sslscan, which relies on these legacy features being available in order to detect them on client system. Ultimately, sslscan is designed to identify bad configurations (rather than to verify good ones), so the support for these legacy features is crucial.

Keeping these features available while also adding support for the new features such as TLSv1.3 would either require maintaining a separate fork of OpenSSL with all the required features enabled, or a complete rewrite of sslscan to use a different library (or to handle the TLS handshake itself). As such, it is likely that sslscan will never support OpenSSL 1.1.0. It is recommended that you continue to build statically against OpenSSL 1.0.1, as describeed in the following section.

This does mean that sslscan is approaching it's end of life - once TLSv1.3 starts to become widespread sslscan will be less and less useful. At that point, it will either need a complete rewrite, or to be replaced with one of the (many) other SSL scanning tools out there.

**Comment by blshkv** [comment]
There is a fork of 1.0.2 tree with new features (chacha) and they sync sources with upstream on a regular basis:
https://github.com/PeterMosmans/openssl
that's what sslyze is using if I'm not wrong.

I created an experimental package 4 months ago and it seems works fine:
https://github.com/pentoo/pentoo-overlay/tree/master/net-analyzer/sslscan-chacha

**Comment by blshkv** [comment]
https://github.com/nabla-c0d3/sslyze/issues/116

**Comment by rbsec** [comment]
@blshkv that's very interesting - I wasn't aware that someone was maintaining a fork with these features. I'll look into getting sslscan building against it, and if it looks reliable then I'll change over to using that.

Thanks

~rbsec

**Comment by rbsec** [comment]
Seems to be working fine, so I've set sslscan to compile against this fork in ef6390d025de11ea743fe4400b56de89befb1695. You probably need to `make clean` and `make static` for this to take effect.

Thanks,

~rbsec
