### ISSUE TITLE
Highlight 112bit CBC3 ciphers

### ISSUE THREAD

**Issue by notoriousturtle** [rbsec/sslscan#131]
Highlight 112bit CBC3 ciphers. 112bit is not strong enough these days.

**Comment by rbsec** [comment]
I'm not aware that anyone has demonstrated any practical attack (or even got close to an attack) against a 112bit cipher, and they're still considered good enough for standards like PCI (which isn't the best source, but it's a benchmark that a lot of people need to follow). More importantly, NIST 800-57 consdiers 112bit symetric encryption to be (roughly) equivilent to 2048bit asymetric encryption) - which is widely view as "good enough".

Either way, sslscan has flagged 3DES ciphers as weak since August last year, and as far as I know that's the only 112 bit cipher (although depending on what version of OpenSSL you build against it might show up as a 168bit cipher).
