### ISSUE TITLE
E: You must put some 'source' URIs in your sources.list

### ISSUE THREAD

**Issue by ealashwali** [rbsec/sslscan#164]
I am using ubuntu 16.4. I need to install the sslscan tool. Unfortunately, following the INSTALL page and trying to `make` then `make install` is not enough to install the tool. So here is what I tried: 
1) I tried to install `git` which then clone the tool. 
2) Navigate to inside the sslscan directoy

Still the openlssl part is unclear. I need the chacha-supported openssl. Can you please tell me the exact steps I need to do to get the tool use the special chcha-supported openssl? 

I tried:
```
apt-get install build-essential git zlib1g-dev
apt-get build-dep openssl
```
But after executing `apt-get build-dep openssl`, I get:
```
Reading package lists... Done
E: You must put some 'source' URIs in your sources.list
```
Can you please clarify what needs to be done? 

I previously tried to manually install the forked ssl. Someone pointed to me that  all what I need to do is `make static` and manually installing the forked openssl is not needed. None of the methods work well. Can you help please?

**Comment by Vignesh9395** [comment]
Hi @ealashwali is this issue resolved? If so please share the solution.
Thanks in advance.

**Comment by frakman1** [comment]
This is still an issue and is not resolved. 
@rbsec The issue should be re-opened.

 @ealashwali used a workaround to install sslscan directly instead of installing the dependency. I just grabbed the latest code today and see this error too. Both in `build_openssl_debian.sh` and when I run `apt-get build-dep openssl` manually.

**Comment by rbsec** [comment]
@frakman1 you need to have source package repos (`deb-src`) enabled in your apt configuration to use the `build-dep` command. They're sometimes included in the default file and commented out - if not then you'll have to add them yourself.

The Debian build script is a leftover from the older version of sslscan - it's no longer required due to the improvements that jtesta made, which adds in support for some of the older protocols. I've removed it - thanks for the reminder.

**Comment by qarmin** [comment]
`sudo sed -Ei 's/^# deb-src /deb-src /' /etc/apt/sources.list` should enable source repos
