### ISSUE TITLE
starttls ldap unknown error

### ISSUE THREAD

**Issue by zetan503** [rbsec/sslscan#167]
I am attempting to sslscan my OpenLDAP servers. They provide Start TLS on 389 and 12389. I got the latest code and did make static, but I get this error when testing those ports:

 ./sslscan --starttls-ldap my-node:389
Version: 1.11.11-rbsec-16-g96ad4ff-static
OpenSSL 1.0.2-chacha (1.0.2g-dev)

STARTLS LDAP connection to test-node:389 failed with unknown error.

**Comment by rbsec** [comment]
That error occurs when the server fails to complete a proper handshake, but doesn't return an error that it doesn't support STARTTLS. It could be something failing in the handshake (like a lack of supported versions/ciphers), or some other kind of error - hard to say more than that I'm afraid.

Would you be able to provide a pcap of the scan failing?

**Comment by ubuntu811** [comment]
I have the same problem with sslscan 1.11.13-rbsec-2-gc9e89bf. 
Running sslscan against the same openldap server via ldaps (:636) works fine, so does ldapsearch -x -ZZ against starttls / 389.

Ciphers on the openldap servers are configured for TLS 1.0 - 1.2. 
TLSProtocolMin        3.1
TLSCipherSuite        "HIGH:!DES-CBC3-SHA:!ECDHE-RSA-DES-CBC3-SHA:!EDH-RSA-DES-CBC3-SHA"

**Comment by eriknolte** [comment]
The LDAP response is a binary BER-encoded structure that contains nulls and can't be searched as a null terminated string.    Here's an example of the response I got from my (Samba) LDAP server:

000000 30 24 02 01 01 78 1f 0a 01 00 04 00 04 00 8a 16  >0$...x..........<
000010 31 2e 33 2e 36 2e 31 2e 34 2e 31 2e 31 34 36 36  >1.3.6.1.4.1.1466<
000020 2e 32 30 30 33 37 00 00 00 00 00 00 00 00 00 00  >.20037..........<

The fix is to use memem (at least on Linux):

diff --git a/sslscan.c b/sslscan.c
index f81fdbd..72e7e47 100644
--- a/sslscan.c
+++ b/sslscan.c
@@ -542,7 +542,7 @@ int tcpConnect(struct sslCheckOptions *options)
         if (!readOrLogAndClose(socketDescriptor, buffer, BUFFERSIZE, options))
             return 0;

-        if (strstr(buffer, ok)) {
+        if (memmem(buffer, BUFFERSIZE, ok, strlen(ok))) {
             printf_verbose("STARTLS LDAP setup complete.\n");
         }
         else if (strstr(buffer, unsupported)) {

**Comment by rbsec** [comment]
@eriknolte thanks - I've merged that change in. The `memmem()` function doesn't exist in Windows - but happily we already have an implementation of it, so that change should work cross-platform.
