### ISSUE TITLE
[sslscan2] Show certificate information for highest found SSL/TLS version

### ISSUE THREAD

**Issue by bc-23** [rbsec/sslscan#190]
Hi,

while I was playing around with the sslscan2 branch, I was wondering why I didn't see any certificate information from the host I tested. After some digging around I saw that the certificate information is only displayed with the SSL/TLS version given via command line or TLS1.0 as fallback.

In https://github.com/bc-23/sslscan/commit/701b9e0d8986ef9b454c23b2a7adfcaa54f16335 I tried a new approach by adding a new option `--tlshighest`. With this option enabled, the certificate checks will not be done via TLS1.0 as fallback, instead they will use the highest seen SSL/TLS version during the protocol test.

Maybe you can take a look on my commit above and let me know what you think about it.
I must admit the last time I have done something in C is a long time ago, so I assume there would be a much better way to implement this as I did, so let me know what could be improved.
Also I think the option name `--tlshighest` does not describe it very well, so if you have a better name, please let me know.

Bye,
Florian

**Comment by rbsec** [comment]
Hi Florian,

Thanks for raising this issue - it's not one I've really come across because I very rarely use the `--show-certificate` option (or the others that it effects).

Rather than adding a new option, I've changed the code in 9c08afb to use `TLS_method()` as a fallback rather than `TLSv1_method()`, which should negotiate anything from TLSv1.0 to TLSv1.3 - so as long as the server supports some kind of TLS it should work. From a quick test it seems to be working as expected - but if you could try it out against the server you were having issues with, that'd be great.

To be honest, I'm not really sure why it didn't just use that method in the first place...

Thanks.

**Comment by bc-23** [comment]
Hi,

I wasn't aware of the `TLS_method()` call, this is a much better solution.
I tested it and everything seems to work fine.

Thank you.
