### ISSUE TITLE
[sslscan2] Support display of HSTS header

### ISSUE THREAD

**Issue by 0x6263** [rbsec/sslscan#191]
Hi again,

I created another commit to support extracting the HSTS header from the HTTP response: https://github.com/bc-23/sslscan/commit/905e1a2b2c03b33427f4b18a86400649d643dc01

Please let me know what you think about it and maybe take a look of the pointer handling of `hsts` if this is correct this way.

Bye,
Florian

**Comment by rbsec** [comment]
Hi Florian,

HSTS is a bit of an interesting one - it's something that I've considered in the past, but always decided against implementing.

The main reason is that sslscan is focused purely on the SSL/TLS level issues - whereas something like HSTS is much more of an application level issue. If we check for a HTTP header like HSTS, it's then much harder to argue whey we're not also checking for something like `Expect-CT`, `Public-Key-Pins`, and things like `upgrade-insecure-requests` in a CSP. And then you're trying to parse potentially quite complicated HTTP headers (as well as handling odd cases like duplicate or invalid HSTS headers) - which isn't really something I'm that keen on doing in sslscan (and especially not in C).

If it was going to be implemented it would probably want to be in its own function rather than the main cipher check (which can be disabled, and also relies on the `--http` option).

@jtesta do you have strong feelings either way on this?

Thanks

**Comment by bc-23** [comment]
Hi,

yes, only check for the HSTS header is not that great and it would be really nice to also check for other certificate related headers. But I also understand your reason about parsing the header in C.
I'm wondering if there maybe is a small library which could be used for parsing which will not add to much dependencies.

Bye

**Comment by jtesta** [comment]
I'd agree that sslscan is better off just focusing on SSL/TLS.  There are already other tools that can analyze HTTP headers, so we'd just be re-inventing the wheel with lots of work (i.e.: string parsing in C) with almost no benefit.

**Comment by rbsec** [comment]
Hi both,

I think for now I'm going to close this issue for the reasons stated above - but thanks for the suggestion.
