### ISSUE TITLE
Trailing spaces in xml <cipher http> attribute

### ISSUE THREAD

**Issue by Sija** [rbsec/sslscan#219]
Padding is done in https://github.com/rbsec/sslscan/blob/1db86fe139d2a9682258b56085e3002c10e33414/sslscan.c#L1750-L1770

But I guess it should be done here instead https://github.com/rbsec/sslscan/blob/1db86fe139d2a9682258b56085e3002c10e33414/sslscan.c#L1588-L1591

**Comment by rbsec** [comment]
Hi @Sija,

Good spot - I've also updated the padding to use `printf()` string formatting, rather than doing it manually.

The HTTP code is really old (I think most of it has been untouched since the original version of sslscan) - so I cleaned up a few other things while I was there (including using HTTP/1.1, which it should have been doing anyway).

I've never really used the `--http` argument, so if this is something that you were using in the real world (rther than just looking at the XML) then I'd be interested to know what your use case is for it. Have you ever encountered servers that return different status codes for different cipher/protocols?

**Comment by Sija** [comment]
> I've never really used the `--http` argument, so if this is something that you were using in the real world (rther than just looking at the XML) then I'd be interested to know what your use case is for it. Have you ever encountered servers that return different status codes for different cipher/protocols?

Different no, I haven't seen that (yet), but for some cipher they do not return at all:

```
  Supported Server Cipher(s):
Preferred 200 OK           TLSv1.2  128 bits    0xC02F ECDHE-RSA-AES128-GCM-SHA256   Curve P-256 DHE 256 691ms
Accepted  200 OK           TLSv1.2  256 bits    0xC030 ECDHE-RSA-AES256-GCM-SHA384   Curve P-256 DHE 256 535ms
Accepted  200 OK           TLSv1.2  128 bits    0xC027 ECDHE-RSA-AES128-SHA256       Curve P-256 DHE 256 679ms
Accepted  200 OK           TLSv1.2  256 bits    0xC028 ECDHE-RSA-AES256-SHA384       Curve P-256 DHE 256 544ms
Accepted  200 OK           TLSv1.2  128 bits    0xC013 ECDHE-RSA-AES128-SHA          Curve P-256 DHE 256 524ms
Accepted  200 OK           TLSv1.2  256 bits    0xC014 ECDHE-RSA-AES256-SHA          Curve P-256 DHE 256 677ms
Accepted  200 OK           TLSv1.2  128 bits    0x009C AES128-GCM-SHA256             673ms
Accepted  200 OK           TLSv1.2  256 bits    0x009D AES256-GCM-SHA384             583ms
Accepted  200 OK           TLSv1.2  128 bits    0x003C AES128-SHA256                 600ms
Accepted  200 OK           TLSv1.2  256 bits    0x003D AES256-SHA256                 585ms
Accepted  200 OK           TLSv1.2  128 bits    0x002F AES128-SHA                    655ms
Accepted  200 OK           TLSv1.2  256 bits    0x0035 AES256-SHA                    690ms
Accepted  TLSv1.2  112 bits    0xC012 TLS_ECDHE_RSA_WITH_3DES_EDE_CBC_SHA 274ms
Accepted  TLSv1.2  112 bits    0x000A TLS_RSA_WITH_3DES_EDE_CBC_SHA 409ms
Preferred 200 OK           TLSv1.1  128 bits    0xC013 ECDHE-RSA-AES128-SHA          Curve P-256 DHE 256 668ms
Accepted  200 OK           TLSv1.1  256 bits    0xC014 ECDHE-RSA-AES256-SHA          Curve P-256 DHE 256 689ms
Accepted  200 OK           TLSv1.1  128 bits    0x002F AES128-SHA                    533ms
Accepted  200 OK           TLSv1.1  256 bits    0x0035 AES256-SHA                    655ms
Accepted  TLSv1.1  112 bits    0xC012 TLS_ECDHE_RSA_WITH_3DES_EDE_CBC_SHA 272ms
Accepted  TLSv1.1  112 bits    0x000A TLS_RSA_WITH_3DES_EDE_CBC_SHA 268ms
Preferred 200 OK           TLSv1.0  128 bits    0xC013 ECDHE-RSA-AES128-SHA          Curve P-256 DHE 256 681ms
Accepted  200 OK           TLSv1.0  256 bits    0xC014 ECDHE-RSA-AES256-SHA          Curve P-256 DHE 256 538ms
Accepted  200 OK           TLSv1.0  128 bits    0x002F AES128-SHA                    679ms
Accepted  200 OK           TLSv1.0  256 bits    0x0035 AES256-SHA                    652ms
Accepted  TLSv1.0  112 bits    0xC012 TLS_ECDHE_RSA_WITH_3DES_EDE_CBC_SHA 414ms
Accepted  TLSv1.0  112 bits    0x000A TLS_RSA_WITH_3DES_EDE_CBC_SHA 279ms
```

Overall I've added support for that in [sslscan.cr](https://github.com/Sija/sslscan.cr) library I'm writing (which internally wraps `sslscan`).

**Comment by Sija** [comment]
Your recent cb7a8aa0c52c71614f95c0a7dea567ad44e03802 commit is a step in a good direction, although along with your changes you've introduced another "bug" - namely outputting `No response` string as a value of `<cipher http="...">` property - which IMO should be printed only for regular output and not be part of the exported data.

**Comment by rbsec** [comment]
I think you're right that an empty `http` attribute might be better than an error message - I've updated it.

I'll have to have a look at that server and see if it's weird behaviour from them, or whether it's a bug in sslscan that means it's not returning the HTTP response code.

**Comment by rbsec** [comment]
Ok, I see what the problem is. Basically , there are two different ways that sslscan checks if a cipher is allowed.

If the cipher is supported by our local openssl (or the version that sslscan was statically compiled against), then it will make a full connection using OpenSSL, and can then make the HTTP request.

However, if it's a cipher that isn't supported locally, then we sslscan manually creates a `ClientHello`, and then checks whether the server returns an error or a `ServerHello` - but it never actually completes the handshake (because it can't). This means that it won't be able to make the HTTP request.

I tried manually connecting with those ciphers from a client that did support them, and the server was returning a `200 OK` as expected. So the issue is on our side, not theirs.

---

I'm not really sure what we can do about this - sslscan will only ever be able to make a proper connection with the ciphers supported in the version of OpenSSL it's using, so we 're not going to be able to actually communicate with servers that use other ciphers. I think all we can really do is mark these ciphers as `N/A` or `Unsupported` or something in the output - although not sure how to make it clear that it's *us* that doesn't support them in the limited space.

To be honest, I'm slightly tempted just to remove the entire `--http` option - I've almost never seen it used, and I'm not sure that this issue can be solved in a nice way - but I'll have a think if there's any other options.

@jtesta do you have any thoughts on this?

**Comment by Sija** [comment]
@rbsec I've opened a dedicated issue (#220) for tracking that, and thus I'm closing this one since it was resolved by your recent commits.
