### ISSUE TITLE
Support html report and  SSL vulnerability scans

### ISSUE THREAD

**Issue by hcjcn** [rbsec/sslscan#258]
It is recommended to support output html reports and general SSL vulnerability scans,thanks.

**Comment by jtesta** [comment]
I think the easiest way to make an HTML report is to make a separate
tool which runs sslscan and parses its XML output.  Python would be my
choice of language, since its makes XML parsing & string manipulation
so easy.

Personally, I don't have the time or motivation to write that tool, but
perhaps you or someone else in the community would like to give that a
shot!

**Comment by rbsec** [comment]
On top of what @jtesta said, there are also a couple of XSLT files on various GitHub repos that you can use to turn the XML into a pretty report.

Adding native HTML reporting (in C) would be a significant time investment, and one that I don't currently have time to make into sslscan.
