### ISSUE TITLE
Provide precompiled binaries for Linux, Mac

### ISSUE THREAD

**Issue by frakman1** [rbsec/sslscan#272]
It would be convenient if there was a precompiled binary available for Linux and Mac and not just for Windows. 
Also an official docker image on dockerhub would be welcome.

For reference:

My latest compilation for x86_64 on Ubuntu 18.04.6 LTS today resulted in this file:
[sslscan_linux_x86_64.zip](https://github.com/rbsec/sslscan/files/10069561/sslscan_linux_x86_64.zip)

``` 
$ ./sslscan --version 
                2.0.15-2-gc450fb1-static
                OpenSSL 1.1.1t-dev  xx XXX xxxx
```

On MacOS Ventura (13.1 Beta ) M1 Max:
[sslscan_mac_arm64.zip](https://github.com/rbsec/sslscan/files/10069563/sslscan_mac_arm64.zip)

On MacOS High Sierra (10.13.6) Intel:
[sslscan_mac_x86_64.zip](https://github.com/rbsec/sslscan/files/10069564/sslscan_mac_x86_64.zip)

**Comment by rbsec** [comment]
Hi @frakman1,

The Windows binary is only really provided because it's so uncommon for people on Windows to have any kind of build environment installed (and because I occasionally need a it as an exe). I'm not really keen on providing static builds for Linux because that's largely just duplicating the work of the people who are packaging it (such as the [Kali team](https://www.kali.org/tools/sslscan/) - and I'm not in a position to do any testing of those binaries on other distributions than my own.

On the Docker site, there in an [image](https://github.com/gbe/docker-sslscan2) that someone made on Alpine in issue #255 - I don't really see any point in duplicating their effort, and to be frank I don't have much interest in maintaining Docker images.

**Comment by frakman1** [comment]
Understood. I didn't realise that the Linux binaries are already packages elsewhere. So maybe instructions about how to install it on Linux would be useful. (e.g. `apt install sslscan`)

**Comment by rbsec** [comment]
I'll vary from distro to distro - some may be packaging older version (Ubuntu had a broken version for a while), but others like Arch ship the current version which you can just installed with `pacman`.
