### ISSUE TITLE
option --onlyvuln only

### ISSUE THREAD

**Issue by anantshri** [rbsec/sslscan#30]
A option to only list red and yellow marked ciphers and only list out compression and simmilar if its vulnerable.

**Comment by rbsec** [comment]
This is simple enough for stuff like compression/renegotation, but because of the original design of sslscan it's a lot more complicated for the ciphers (due to the output being in multiple places throughout the testCipher() function, and in some cases you can't tell if a cipher is good or bad until near the end of the function. As a result, implmenting this would require rewriting a lot of testCipher(), and also the hearbleed function would need to be redesigned.

I'll have a think and see if I can come up with a simper way to do this, because I don't really have time for that kind of rewrite at the moment (although if you want to write something and send a PR, please feel free).

If you want to do you own fancy output (for reports, or whatever), then it's probably best to generate the XML output, and then you can parse that (either with your own script, or XSLT).

**Comment by anantshri** [comment]
Thnaks for the tips
