### ISSUE TITLE
xml output additions

### ISSUE THREAD

**Issue by anantshri** [rbsec/sslscan#33]
please add indicators like weak, good, ok or risky to xml output of cipher suites.

**Comment by rbsec** [comment]
The XML output for the ciphers lists the strength (as well as other factors), which you can use to determine the how risky you think the cipher is. From a code perspective, I don't really see how reading "strength=weak" is any easier than "bits=40".

I'd also rather not try and put that kind of logic in the XML files - that should be in whatever tool is interpreting them. If a new vuln is announced next weak in, say, TLS 1.0 + AES, then your parsing tool will still flag that on any old XML files you have, because the information is there. If that logic was in sslscan when it wrote the file, they wouldn't, and you'd have to go back and re-scan them.

Parsing the files for the vulns should be pretty trivial - most of it is just simple pattern matching against the XML fields. The only one that's a tiny bit more complicated is POODLE - but that just needs you to match a version of SSLv3 and a cipher that doesn't include "RC4".
