### ISSUE TITLE
Heartbleed test TLS version

### ISSUE THREAD

**Issue by alexcowperthwaite** [rbsec/sslscan#38]
Hearbleed test repeats the same test for all TLS versions. 
The testHeartbleed function opens a raw TCP socket, then sends a hardcoded clientHello message:
char hello[] = {0x16,**0x03,0x02**,0x00...

This ClientHello message also contains a hardcoded TLS version numbers.  The output indicates that TLS version 1.0, 1.1 and 1.2 are tested, when the same test (TLS 1.1) is executed three times.

This likely also applies to the hardcoded Heartbeat message.

**Comment by rbsec** [comment]
That was a stupid bug - thanks for pointing that out. Interestingly I'd had servers where heartbleed is detected on some TLS versions but not others (which shouldn't have been possible with that code) - strange.

To be honest I've never been very happy with the heartbleed, I did have a look at trying to do most of it through OpenSSL (rather than doing the ClientHello manually), but there didn't seem to be a nice way of doing it.
