### ISSUE TITLE
LibreSSL support

### ISSUE THREAD

**Issue by MercSec** [rbsec/sslscan#41]
I tried to compile the Application on OpenBSD using LibreSSL.
LibreSSL does not support everything OpenSSL supports. An example would be the compression or NIST/SSLv2.

The following Errors where reported by GCC:

#  gcc -lssl -o sslscan sslscan.c
sslscan.c: In function 'testCompression':
sslscan.c:746: error: 'SSL_SESSION' has no member named 'compress_meth'
sslscan.c:749: error: 'SSL_SESSION' has no member named 'compress_meth'
sslscan.c: In function 'ssl_print_tmp_key':
sslscan.c:1158: warning: assignment makes pointer from integer without a cast
sslscan.c: In function 'main':
sslscan.c:3116: error: 'VERSION' undeclared (first use in this function)
sslscan.c:3116: error: (Each undeclared identifier is reported only once
sslscan.c:3116: error: for each function it appears in.)
#

**Comment by rbsec** [comment]
LibreSSL has already removed some key features (such as SSLv2 as you mentioned, as well as some old insecure algorithms), and they seem to be intending to remove more insecure features as time goes on (which is fantastic for a system library).

However, the whole point of sslscan is to identify systems that still support these old and insecure features/protocols/algorithms, so building it against a library that doesn't support them doesn't make sense, as it'll be unable to detect them. Even worse, it'll come back with a clean report, which will give the false impression that the server is securely configured.

The sslscan source is already a bit of a mess because of all the ifdefs to account for various versions of OpenSSL (and that SSLv2 and SSLv3 are now disabled by default in a lot of distros). I don't really see much value to trying to get sslscan building against a library that won't support the key features it needs, and could actually be counterproductive from a security point of view.

Since SSLv2 and SSLv3 are now disabled by default in a lot of places, the best way to use sslscan is from a statically built binary (which will support the older insecure protocols, regardless of what your system SSL library supports).

Rather than trying to make sslscan work with LibreSSL, I'd recommend trying to statically build it against OpenSSL (`make static`). If you're looking to add it to the repositories for OpenBSD, then a statically built binary would be the best option (which is what Kali Linux does).

~rbsec
